#!/usr/bin/env python3
"""
03_generate_publication_figures.py
==============================================================================
Generates all publication-grade figures (Figures 2–6 (Figure 1 generated by 04_generate_research_design_figure.py)) and Supplementary
Information figures (Figures S1–S6) for:

"Technological Modernization Fails to Improve Fleet Capacity Utilization in
Turkish Marine Capture Fisheries" (ICES Journal of Marine Science, ICESJMS-2026-474)

Standards Applied:
- Colorblind-safe academic palette (Okabe-Ito / ColorBrewer)
- Geographic counter-clockwise ordering: Mediterranean -> Aegean -> Marmara ->
  West Black Sea -> East Black Sea
- Standardized country nomenclature: 'Türkiye'
- Dual export format: Vector PDF and 300+ DPI raster PNG
==============================================================================
"""

import os
import json
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.patches import Patch, Ellipse
from matplotlib.lines import Line2D
import matplotlib.transforms as transforms
from statsmodels.nonparametric.smoothers_lowess import lowess
from sklearn.ensemble import RandomForestRegressor

# Optional spatial import
try:
    import geopandas as gpd
    HAS_GEOPANDAS = True
except ImportError:
    HAS_GEOPANDAS = False

# ------------------------------------------------------------------------------
# 1. Directory and Path Setup
# ------------------------------------------------------------------------------
script_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(script_dir) if os.path.basename(script_dir) == 'scripts' else script_dir
data_dir = os.path.join(repo_root, 'data')
fig_dir = os.path.join(repo_root, 'figures')
os.makedirs(fig_dir, exist_ok=True)

# ------------------------------------------------------------------------------
# 2. Master Academic Aesthetics & Palettes
# ------------------------------------------------------------------------------
plt.rcParams.update({
    'font.family': 'sans-serif',
    'font.sans-serif': ['Arial', 'Helvetica', 'DejaVu Sans'],
    'font.size': 9.5,
    'axes.labelsize': 9.5,
    'axes.titlesize': 10.5,
    'xtick.labelsize': 8.5,
    'ytick.labelsize': 8.5,
    'legend.fontsize': 8.5,
    'figure.dpi': 150,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.08,
    'axes.linewidth': 0.8,
    'axes.edgecolor': '#333333',
    'xtick.major.width': 0.8,
    'ytick.major.width': 0.8,
    'axes.spines.top': False,
    'axes.spines.right': False,
    'axes.grid': True,
    'grid.color': '#E5E7EB',
    'grid.linestyle': '--',
    'grid.linewidth': 0.5,
    'axes.axisbelow': True,
    'legend.framealpha': 0.96,
    'legend.edgecolor': '#CBD5E1',
})

GEO_REGIONS = ['Mediterranean', 'Aegean', 'Marmara', 'West_Black_Sea', 'East_Black_Sea']
GEO_LABELS = [
    'Mediterranean (Türkiye)', 'Aegean (Türkiye)', 'Marmara (Türkiye)',
    'West Black Sea (Türkiye)', 'East Black Sea (Türkiye)'
]
GEO_CLEAN_LABELS = ['Mediterranean', 'Aegean', 'Marmara', 'West Black Sea', 'East Black Sea']
GEO_MAP = dict(zip(GEO_REGIONS, GEO_LABELS))

GEO_COLORS = {
    'Mediterranean': '#1B4F72',   # Deep Sapphire Blue
    'Aegean':        '#238B45',   # Marine Emerald Green
    'Marmara':       '#D95F02',   # Warm Amber-Orange
    'West_Black_Sea':'#C0392B',   # Terracotta Crimson
    'East_Black_Sea':'#762A83'    # Imperial Amethyst Violet
}

GEO_MARKERS = {
    'Mediterranean': 's',
    'Aegean':        'o',
    'Marmara':       '^',
    'West_Black_Sea':'D',
    'East_Black_Sea':'v'
}


def confidence_ellipse(x, y, ax, n_std=1.5, facecolor='none', **kwargs):
    """Utility to draw bivariate confidence ellipses."""
    if len(x) != len(y) or len(x) < 3:
        return
    cov = np.cov(x, y)
    pearson = cov[0, 1] / np.sqrt(cov[0, 0] * cov[1, 1])
    ell_radius_x = np.sqrt(1 + pearson)
    ell_radius_y = np.sqrt(1 - pearson)
    ellipse = Ellipse((0, 0), width=ell_radius_x * 2, height=ell_radius_y * 2,
                      facecolor=facecolor, **kwargs)
    scale_x = np.sqrt(cov[0, 0]) * n_std
    mean_x = np.mean(x)
    scale_y = np.sqrt(cov[1, 1]) * n_std
    mean_y = np.mean(y)
    transf = transforms.Affine2D().rotate_deg(45).scale(scale_x, scale_y).translate(mean_x, mean_y)
    ellipse.set_transform(transf + ax.transData)
    return ax.add_patch(ellipse)


# ==============================================================================
# FIGURE 2: Maritime Basins, Fleet Distribution & Infrastructure Map
# ==============================================================================
def generate_figure_2():
    print("Generating Figure 2 (Cartographic GIS Infrastructure Map)...")
    if not HAS_GEOPANDAS:
        print("  [!] geopandas not installed. Skipping Figure 1.")
        return

    prov_path = os.path.join(data_dir, 'geojson', 'turkey_provinces.geojson')
    ne_path = os.path.join(data_dir, 'geojson', 'ne_50m_euro_med_countries.geojson')
    ports_path = os.path.join(data_dir, 'data_coastal_ports_geocoded.csv')

    if not (os.path.exists(prov_path) and os.path.exists(ne_path) and os.path.exists(ports_path)):
        print("  [!] GIS assets missing in data/. Skipping Figure 1.")
        return

    provinces = gpd.read_file(prov_path)
    surrounding = gpd.read_file(ne_path)
    surrounding_non_tr = surrounding[~surrounding['NAME'].isin(['Turkey', 'Türkiye'])].copy()
    ports_all = pd.read_csv(ports_path)

    med_provs = ['Hatay', 'Adana', 'Mersin', 'Antalya']
    aeg_provs = ['Muğla', 'Aydın', 'İzmir', 'Edirne']
    mar_provs = ['Çanakkale', 'Balıkesir', 'Bursa', 'Yalova', 'Tekirdağ']
    wbs_provs = ['Kırklareli', 'İstanbul', 'Kocaeli', 'Sakarya', 'Düzce', 'Zonguldak', 'Bartın', 'Kastamonu', 'Sinop']
    ebs_provs = ['Samsun', 'Ordu', 'Giresun', 'Trabzon', 'Rize', 'Artvin']

    def assign_basin(name):
        if name in med_provs: return 'Mediterranean'
        if name in aeg_provs and name != 'Edirne': return 'Aegean'
        if name in mar_provs: return 'Marmara'
        if name in wbs_provs: return 'West Black Sea'
        if name in ebs_provs: return 'East Black Sea'
        return 'Inland'

    provinces['Basin'] = provinces['name'].apply(assign_basin)

    palette = {
        'Mediterranean': '#1B4F72',
        'Aegean':        '#238B45',
        'Marmara':       '#D95F02',
        'West Black Sea':'#C0392B',
        'East Black Sea':'#762A83',
        'Inland':        '#E5E7EB'
    }

    fig, ax = plt.subplots(figsize=(13.8, 8.4), dpi=300)
    ax.set_facecolor('#EBF3F8')

    surrounding_non_tr.plot(ax=ax, color='#F3F4F6', edgecolor='#CBD5E1', linewidth=0.6, zorder=1)
    provinces[provinces['Basin'] == 'Inland'].plot(ax=ax, color=palette['Inland'], edgecolor='#D1D5DB', linewidth=0.5, zorder=2)

    for basin in ['Mediterranean', 'Aegean', 'Marmara', 'West Black Sea', 'East Black Sea']:
        subset = provinces[provinces['Basin'] == basin]
        subset.plot(ax=ax, color=palette[basin], edgecolor='#FFFFFF', linewidth=0.7, alpha=0.92, zorder=3)

    country_labels = [
        (24.8, 41.8, 'BULGARIA'), (23.5, 39.5, 'GREECE'), (42.5, 42.0, 'GEORGIA'),
        (44.0, 40.2, 'ARMENIA'), (38.2, 35.2, 'SYRIA'), (33.3, 35.1, 'CYPRUS')
    ]
    for cx, cy, cname in country_labels:
        ax.text(cx, cy, cname, fontsize=8.5, color='#94A3B8', fontweight='bold', ha='center', va='center', zorder=2, style='italic', alpha=0.9)

    sea_labels = [
        (36.6, 43.30, 'B L A C K   S E A'),
        (28.2, 40.75, 'SEA OF\nMARMARA'),
        (24.8, 38.4, 'A E G E A N\nS E A'),
        (32.5, 35.4, 'M E D I T E R R A N E A N   S E A')
    ]
    for sx, sy, sname in sea_labels:
        ax.text(sx, sy, sname, fontsize=10.0, color='#4A6F8A', fontweight='bold', ha='center', va='center', zorder=2, alpha=0.85, style='italic')

    ax.text(35.2, 39.1, 'T Ü R K İ Y E', fontsize=17, color='#475569', fontweight='bold', ha='center', va='center', zorder=4, alpha=0.90)

    p_lon = 'plot_lon' if 'plot_lon' in ports_all.columns else 'coast_lon'
    p_lat = 'plot_lat' if 'plot_lat' in ports_all.columns else 'coast_lat'

    ports_comm = ports_all[ports_all['facility_type'] == 'Balıkçı Barınağı']
    ports_cekek = ports_all[ports_all['facility_type'] == 'Çekek Yeri']
    ports_shelter = ports_all[~ports_all['facility_type'].isin(['Balıkçı Barınağı', 'Çekek Yeri'])]

    ax.scatter(ports_shelter[p_lon], ports_shelter[p_lat], color='#0284C7', marker='D', s=16, zorder=5, edgecolor='#FFFFFF', linewidth=0.5, alpha=0.9)
    ax.scatter(ports_cekek[p_lon], ports_cekek[p_lat], color='#D95F02', marker='^', s=20, zorder=6, edgecolor='#FFFFFF', linewidth=0.6, alpha=0.95)
    ax.scatter(ports_comm[p_lon], ports_comm[p_lat], color='#0F172A', marker='o', s=22, zorder=7, edgecolor='#FFFFFF', linewidth=0.65, alpha=0.95)

    major_hubs = [
        (40.23, 41.00, 'Trabzon', 'top'), (36.33, 41.29, 'Samsun', 'top'), (35.15, 42.02, 'Sinop', 'bottom'),
        (31.79, 41.45, 'Zonguldak', 'bottom'), (29.00, 41.05, 'Istanbul', 'top'), (27.97, 40.35, 'Bandırma', 'bottom'),
        (27.14, 38.42, 'İzmir', 'right'), (27.43, 37.03, 'Bodrum', 'bottom'), (30.70, 36.88, 'Antalya', 'bottom'),
        (34.64, 36.81, 'Mersin', 'bottom'), (36.17, 36.58, 'İskenderun', 'right')
    ]
    for lon, lat, name, pos in major_hubs:
        offset_y = 0.22 if pos == 'top' else -0.28
        offset_x = 0.22 if pos == 'right' else (-0.22 if pos == 'left' else 0)
        ax.text(lon + offset_x, lat + offset_y, name, fontsize=8.8, fontweight='bold',
                ha='center' if pos in ['top', 'bottom'] else ('left' if pos == 'right' else 'right'),
                va='center', color='#0F172A', zorder=8,
                bbox=dict(boxstyle='round,pad=0.20', facecolor='white', alpha=0.92, edgecolor='#CBD5E1', linewidth=0.6))

    annotations = [
        (40.2, 42.75, r"EAST BLACK SEA BASIN" "\n" r"Dominant: Industrial Purse Seines & Pelagic Trawls" "\n" r"Target: Anchovy ($\it{Engraulis\ encrasicolus}$), Sprat, Horse Mackerel" "\n" r"Fleet Share: ~45% national catch, 24% vessels", '#762A83'),
        (32.8, 42.75, r"WEST BLACK SEA BASIN" "\n" r"Dominant: Demersal Trawls & Bottom Gillnets" "\n" r"Target: Turbot ($\it{Scophthalmus\ maximus}$), Whiting, Bonito" "\n" r"Fleet Share: ~15% national catch, 15% vessels", '#C0392B'),
        (27.8, 41.80, r"SEA OF MARMARA BASIN" "\n" r"Dominant: Artisanal Fixed Gear & Coastal Seiners" "\n" r"Target: Bluefish ($\it{Pomatomus\ saltatrix}$), Mullet, Shrimps" "\n" r"Fleet Share: ~12% national catch, 19% vessels", '#D95F02'),
        (24.5, 36.70, r"AEGEAN SEA BASIN" "\n" r"Dominant: Polyvalent Small-Scale & Artisanal Netters" "\n" r"Target: Sea Bream, Sea Bass, Red Mullet, Cephalopods" "\n" r"Fleet Share: ~10% national catch, 24% vessels", '#238B45'),
        (32.6, 34.40, r"MEDITERRANEAN SEA BASIN" "\n" r"Dominant: Bottom Trawls & Multispecies Longlines" "\n" r"Target: Red Mullet ($\it{Mullus\ barbatus}$), Shrimps, Groupers" "\n" r"Fleet Share: ~18% national catch, 18% vessels", '#1B4F72')
    ]
    for x, y, text, color in annotations:
        ax.text(x, y, text, fontsize=7.8, color='#0F172A', ha='center', va='center', zorder=8,
                linespacing=1.25,
                bbox=dict(boxstyle='round,pad=0.35', facecolor='#FFFFFF', alpha=0.96, edgecolor=color, linewidth=1.2))

    # North arrow
    ax.annotate('N', xy=(43.5, 36.7), xytext=(43.5, 35.85),
                arrowprops=dict(facecolor='#0F172A', edgecolor='white', width=2.5, headwidth=8.0, headlength=10.0),
                ha='center', va='center', fontsize=12.0, fontweight='bold', color='#0F172A', zorder=9)

    # Scale bar
    ax.plot([40.5, 42.9], [34.8, 34.8], color='#0F172A', linewidth=2.8, solid_capstyle='butt', zorder=9)
    ax.text(41.7, 35.05, '200 km', fontsize=8.8, fontweight='bold', ha='center', va='bottom', color='#0F172A', zorder=9)

    ax.set_xlim(23.2, 45.2)
    ax.set_ylim(33.8, 44.0)
    ax.set_xlabel('Longitude (°E)', fontsize=10.0, fontweight='bold', labelpad=6)
    ax.set_ylabel('Latitude (°N)', fontsize=10.0, fontweight='bold', labelpad=6)
    ax.tick_params(axis='both', which='major', labelsize=8.8)

    legend_elements = [
        mpatches.Patch(facecolor='#762A83', edgecolor='white', label='East Black Sea (Industrial Pelagic)'),
        mpatches.Patch(facecolor='#C0392B', edgecolor='white', label='West Black Sea (Demersal & Pelagic)'),
        mpatches.Patch(facecolor='#D95F02', edgecolor='white', label='Marmara (Semi-Industrial & Small-Scale)'),
        mpatches.Patch(facecolor='#238B45', edgecolor='white', label='Aegean (Artisanal Small-Scale)'),
        mpatches.Patch(facecolor='#1B4F72', edgecolor='white', label='Mediterranean (Demersal Trawl & Longline)'),
        Line2D([0], [0], marker='o', color='w', label='Primary Commercial Fishing Ports (N = 236)', markerfacecolor='#0F172A', markeredgecolor='white', markersize=7.0),
        Line2D([0], [0], marker='^', color='w', label='Boat Slipways & Haul-out Areas (N = 72)', markerfacecolor='#D95F02', markeredgecolor='white', markersize=7.5),
        Line2D([0], [0], marker='D', color='w', label='Coastal Landing Shelters & Havens (N = 78)', markerfacecolor='#0284C7', markeredgecolor='white', markersize=6.0),
        Line2D([0], [0], marker='s', color='w', label='Major Regional Landing Hubs (Annotated)', markerfacecolor='white', markeredgecolor='#0F172A', markersize=6.5)
    ]
    ax.legend(handles=legend_elements, loc='lower right', frameon=True, facecolor='white',
              framealpha=0.96, edgecolor='#CBD5E1', fontsize=8.8, title='Maritime Basins & Infrastructure (BSGM 2026)', title_fontsize=9.8)

    ax.grid(color='#CBD5E1', linestyle=':', linewidth=0.5, alpha=0.6, zorder=0)
    plt.tight_layout()

    out_png = os.path.join(fig_dir, 'Fig2_Turkiye_maritime_basins_fisheries_map.png')
    out_pdf = os.path.join(fig_dir, 'Fig2_Turkiye_maritime_basins_fisheries_map.pdf')
    plt.savefig(out_png, dpi=300, bbox_inches='tight')
    plt.savefig(out_pdf, dpi=300, bbox_inches='tight')
    plt.close()
    print("  [✓] Successfully generated Figure 2 (PNG & PDF).")


# ==============================================================================
# FIGURE 3: Time Series of Catch Volume & Real Landings Value (2000–2024)
# ==============================================================================
def generate_figure_3():
    print("Generating Figure 3 (Landings & Real Value Time Series)...")
    csv_path = os.path.join(data_dir, 'panel_fisheries_modernization_2000_2024.csv')
    df = pd.read_csv(csv_path)
    df = df[df['Region'] != 'Total'].copy()
    df['Year'] = pd.to_numeric(df['Year'])
    df['Amount_ktons'] = df['Catch_Volume_Tonnes'] / 1000.0
    df['Real_Val_MTRY'] = df['Real_Catch_Value_Thousand_TRY'] / 1000.0

    geo_order = GEO_REGIONS
    geo_labels = GEO_MAP
    palette = GEO_COLORS
    markers = GEO_MARKERS

    fig, axes = plt.subplots(2, 2, figsize=(14, 10), dpi=300, sharex=True)
    panels = [
        (axes[0, 0], 'Amount_ktons', 'Annual Landings (thousand tonnes)', '(a) Marine Capture Landings by Maritime Basin (2000–2024)', True),
        (axes[0, 1], 'Real_Val_MTRY', 'Real Catch Value (million TRY, constant 2015 prices)', '(b) Real Catch Value by Maritime Basin (2000–2024)', False),
        (axes[1, 0], 'Total_Vessels', 'Number of Registered Vessels', '(c) Fleet Size (Vessel Numbers) by Maritime Basin', False),
        (axes[1, 1], 'Total_GRT', 'Gross Registered Tonnage (GRT)', '(d) Total Fleet Capacity (GRT) by Maritime Basin', False)
    ]

    for ax, col, ylabel, title, is_panel_a in panels:
        ax.axvspan(2012, 2018, color='#F1F5F9', alpha=0.9, zorder=1)
        ax.axvline(2012, color='#94A3B8', linestyle='--', linewidth=0.9, alpha=0.7, zorder=2)
        ax.axvline(2018, color='#94A3B8', linestyle='--', linewidth=0.9, alpha=0.7, zorder=2)

        for reg in geo_order:
            sub = df[df['Region'] == reg].sort_values('Year')
            ax.plot(sub['Year'], sub[col], marker=markers[reg], markersize=5.5,
                    color=palette[reg], label=geo_labels[reg], linewidth=2.0, alpha=0.95,
                    markeredgecolor='white', markeredgewidth=0.7, zorder=3)

        if is_panel_a:
            ax.set_ylim(-10, 375)
            ax.text(2015, 335, 'Decommissioning Scheme\n(2012–2018)', ha='center', va='center',
                    fontsize=9.2, color='#334155', fontweight='bold', style='italic',
                    bbox=dict(boxstyle='round,pad=0.35', facecolor='#FFFFFF', alpha=0.95, edgecolor='#94A3B8', lw=0.8),
                    zorder=4)

        if col == 'Real_Val_MTRY': ax.set_ylim(0, 1600)
        elif col == 'Total_Vessels': ax.set_ylim(1000, 6500)
        elif col == 'Total_GRT': ax.set_ylim(5000, 105000)

        ax.set_ylabel(ylabel, fontsize=11.5, fontweight='bold', labelpad=8)
        ax.set_title(title, fontsize=12.5, fontweight='bold', pad=10, loc='left')
        ax.tick_params(axis='both', which='major', labelsize=10.5)
        ax.grid(True, linestyle=':', color='#E2E8F0', linewidth=0.7, alpha=0.8, zorder=0)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.set_xlim(1999.5, 2024.5)

    axes[1, 0].set_xlabel('Year', fontsize=11.5, fontweight='bold', labelpad=8)
    axes[1, 1].set_xlabel('Year', fontsize=11.5, fontweight='bold', labelpad=8)

    handles, labels = axes[0, 0].get_legend_handles_labels()
    handles.append(Patch(facecolor='#F1F5F9', edgecolor='#94A3B8', linestyle='--', label='Decommissioning Period (2012–2018)'))
    labels.append('Decommissioning Period (2012–2018)')

    fig.legend(handles, labels, loc='lower center', ncol=3, frameon=True, facecolor='white',
               edgecolor='#CBD5E1', fontsize=10.5, bbox_to_anchor=(0.5, 0.008), columnspacing=2.5)

    plt.subplots_adjust(bottom=0.11, top=0.95, hspace=0.25, wspace=0.22)

    out_png = os.path.join(fig_dir, 'Fig3_landings_and_value_timeseries_2000_2024.png')
    out_pdf = os.path.join(fig_dir, 'Fig3_landings_and_value_timeseries_2000_2024.pdf')
    plt.savefig(out_png, dpi=300, bbox_inches='tight')
    plt.savefig(out_pdf, dpi=300, bbox_inches='tight')
    plt.close()
    print("  [✓] Successfully generated Figure 3 (PNG & PDF).")


# ==============================================================================
# FIGURE 4: Technology Adoption & Modernization Index Trajectory
# ==============================================================================
def generate_figure_4():
    print("Generating Figure 4 (Technology Adoption & MI Trajectory)...")
    tech_csv = os.path.join(data_dir, 'regional_tech_adoption_rates_2007_2024.csv')
    res_json = os.path.join(data_dir, 'fleet_modernization_model_results.json')
    panel_csv = os.path.join(data_dir, 'panel_fisheries_modernization_2000_2024.csv')

    pivot_tech = pd.read_csv(tech_csv, index_col=0)
    pivot_tech.columns = [int(c) for c in pivot_tech.columns]
    pivot_tech = pivot_tech.reindex(GEO_REGIONS)

    with open(res_json) as f:
        rb = json.load(f)
    mi_data = rb.get('mi_by_region_year', {})

    panel = pd.read_csv(panel_csv)
    panel = panel[panel['Region'] != 'Total'].copy()
    if 'CU_Boot_BC' in panel.columns:
        panel['CU_Score'] = panel['CU_Boot_BC']

    fig = plt.figure(figsize=(9.8, 12.2), dpi=300)
    gs = gridspec.GridSpec(3, 1, height_ratios=[0.60, 1.0, 1.05],
                           hspace=0.34,
                           left=0.155, right=0.965, top=0.925, bottom=0.105)

    # (a) Heatmap
    ax_a = fig.add_subplot(gs[0])
    extent = [2006.5, 2024.5, 4.5, -0.5]
    im = ax_a.imshow(pivot_tech.values, aspect='auto', extent=extent,
                     cmap='YlGnBu', vmin=0.10, vmax=0.40, interpolation='nearest')
    ax_a.grid(False)

    for i in range(len(GEO_REGIONS)):
        for j, yr in enumerate(range(2007, 2025)):
            val = pivot_tech.values[i, j]
            color = 'white' if val > 0.28 else '#0F172A'
            ax_a.text(yr, i, f'{val*100:.0f}%', ha='center', va='center',
                      fontsize=8.8, color=color, fontweight='bold')

    ax_a.set_yticks(range(len(GEO_REGIONS)))
    ax_a.set_yticklabels(GEO_CLEAN_LABELS, fontsize=10.5, fontweight='bold')
    ax_a.set_xlim(2006.5, 2024.5)
    ax_a.set_xticks(range(2008, 2025, 2))
    ax_a.set_xticks(range(2007, 2025, 1), minor=True)
    ax_a.set_xticklabels([str(y) for y in range(2008, 2025, 2)], fontsize=10.0)

    for y in np.arange(0.5, 4.5, 1): ax_a.axhline(y, color='white', linewidth=0.8, alpha=0.9)
    for x in np.arange(2007.5, 2024.5, 1): ax_a.axvline(x, color='white', linewidth=0.5, alpha=0.5)

    for spine in ax_a.spines.values():
        spine.set_visible(True); spine.set_linewidth(0.8); spine.set_color('#333333')

    ax_a.set_title('(a) Equipment Adoption Rate by Basin (2007–2024)', loc='left', fontsize=12.2, fontweight='bold', pad=9)

    cax = fig.add_axes([0.745, 0.942, 0.22, 0.012])
    cbar = fig.colorbar(im, cax=cax, orientation='horizontal')
    cbar.set_ticks([0.10, 0.20, 0.30, 0.40])
    cbar.set_ticklabels(['10%', '20%', '30%', '40%'])
    cbar.ax.tick_params(labelsize=8.5, pad=2)
    cbar.outline.set_linewidth(0.7)
    cbar.ax.set_title('Adoption Rate', fontsize=8.8, fontweight='bold', pad=3)

    # (b) MI Trajectory
    ax_b = fig.add_subplot(gs[1], sharex=ax_a)
    for reg in GEO_REGIONS:
        if reg in mi_data:
            yrs = mi_data[reg]['years']
            vals = mi_data[reg]['mi_values']
            filtered = [(y, v) for y, v in zip(yrs, vals) if y >= 2007]
            f_yrs, f_vals = zip(*filtered)
            ax_b.plot(f_yrs, f_vals, label=GEO_MAP[reg], color=GEO_COLORS[reg],
                      lw=2.3, marker=GEO_MARKERS[reg], ms=5.5, markeredgecolor='white', markeredgewidth=0.7, zorder=3)

    ax_b.set_ylabel('Modernization Index (PC1)', fontsize=11.5, fontweight='bold', labelpad=8)
    ax_b.tick_params(axis='both', labelsize=10.0)
    ax_b.axhline(0, color='#64748B', ls='-', lw=0.8, alpha=0.6, zorder=1)
    ax_b.set_xlim(2006.5, 2024.5)
    ax_b.set_xticks(range(2008, 2025, 2))
    ax_b.set_xticks(range(2007, 2025, 1), minor=True)
    ax_b.set_xticklabels([str(y) for y in range(2008, 2025, 2)], fontsize=10.0)
    ax_b.set_title('(b) Fleet Modernization Index (PC1) Trajectory (2007–2024)', loc='left', fontsize=12.2, fontweight='bold', pad=8)

    # (c) Rolling Correlation
    ax_c = fig.add_subplot(gs[2], sharex=ax_a)
    ax_c.axhspan(0, 1.05, color='#ECFDF5', alpha=0.7, zorder=0)
    ax_c.axhspan(-1.05, 0, color='#FEF2F2', alpha=0.7, zorder=0)

    ax_c.text(2007.2, 0.88, "Productive Catch-Up Zone (r > 0)", fontsize=9.6, color='#047857', fontweight='bold', style='italic',
              bbox=dict(boxstyle='round,pad=0.3', facecolor='#ECFDF5', edgecolor='#A7F3D0', alpha=0.92, lw=0.7), zorder=4)
    ax_c.text(2018.5, -0.88, "Technology Treadmill & Rent Dissipation Zone (r < 0)", fontsize=9.6, color='#B91C1C', fontweight='bold', style='italic',
              ha='center', bbox=dict(boxstyle='round,pad=0.3', facecolor='#FEF2F2', edgecolor='#FECACA', alpha=0.92, lw=0.7), zorder=4)

    for reg in GEO_REGIONS:
        sub = panel[panel['Region'] == reg].sort_values('Year')
        rolling_corr = sub['Modernization_Index'].rolling(5, min_periods=4).corr(sub['CU_Score'])
        sub_post = sub[sub['Year'] >= 2007]
        rc_post = rolling_corr[sub['Year'] >= 2007]
        ax_c.plot(sub_post['Year'], rc_post, label=GEO_MAP[reg], color=GEO_COLORS[reg],
                  lw=2.3, marker=GEO_MARKERS[reg], ms=5.5, markeredgecolor='white', markeredgewidth=0.7, zorder=3)

    ax_c.set_xlabel('Year', fontsize=11.5, fontweight='bold', labelpad=7)
    ax_c.set_ylabel('5-Yr Rolling Correlation\n(MI vs Capacity Utilization)', fontsize=11.5, fontweight='bold', labelpad=8)
    ax_c.tick_params(axis='both', labelsize=10.0)
    ax_c.axhline(0, color='#1E293B', ls='-', lw=0.9, alpha=0.7, zorder=2)
    ax_c.set_ylim(-1.05, 1.05)
    ax_c.set_xlim(2006.5, 2024.5)
    ax_c.set_xticks(range(2008, 2025, 2))
    ax_c.set_xticks(range(2007, 2025, 1), minor=True)
    ax_c.set_xticklabels([str(y) for y in range(2008, 2025, 2)], fontsize=10.0)
    ax_c.set_title('(c) Dynamic Modernization–Efficiency Correlation (5-Year Rolling Window)', loc='left', fontsize=12.2, fontweight='bold', pad=8)

    fig.align_ylabels([ax_b, ax_c])

    handles, labels = ax_b.get_legend_handles_labels()
    fig.legend(handles, labels, loc='lower center', ncol=5, frameon=True, facecolor='white',
               edgecolor='#CBD5E1', fontsize=9.2, columnspacing=0.8, handletextpad=0.4,
               handlelength=1.5, borderaxespad=0.2, bbox_to_anchor=(0.50, 0.012))

    out_png = os.path.join(fig_dir, 'Fig4_tech_adoption_MI_trajectory.png')
    out_pdf = os.path.join(fig_dir, 'Fig4_tech_adoption_MI_trajectory.pdf')
    fig.savefig(out_png, dpi=300)
    fig.savefig(out_pdf, dpi=300)
    plt.close()
    print("  [✓] Successfully generated Figure 4 (PNG & PDF).")


# ==============================================================================
# FIGURE 5: Scale Efficiency Decomposition
# ==============================================================================
def generate_figure_5():
    print("Generating Figure 5 (Scale Efficiency Decomposition)...")
    res_json = os.path.join(data_dir, 'fleet_modernization_model_results.json')
    with open(res_json) as f:
        rb = json.load(f)

    decomp = rb.get('dea_decomposition', {}).get('by_region', {})
    crs_vals = [decomp[r]['CRS_TE'] for r in GEO_REGIONS if r in decomp]
    vrs_vals = [decomp[r]['VRS_TE'] for r in GEO_REGIONS if r in decomp]
    se_vals  = [decomp[r]['Scale_Eff'] for r in GEO_REGIONS if r in decomp]
    labels_geose = [GEO_MAP.get(r, r).replace(' (Türkiye)', '\n(Türkiye)') for r in GEO_REGIONS if r in decomp]

    fig, ax = plt.subplots(figsize=(10.5, 4.8), dpi=300)
    x = np.arange(len(labels_geose))
    w = 0.24

    b1 = ax.bar(x - w, crs_vals, w, color='#64748B', alpha=0.92, edgecolor='white', linewidth=0.7)
    b2 = ax.bar(x,     vrs_vals, w, color='#1E3A8A', alpha=0.92, edgecolor='white', linewidth=0.7)
    b3 = ax.bar(x + w, se_vals,  w, color='#D97706', alpha=0.92, edgecolor='white', linewidth=0.7)
    ax.axhline(1.0, color='#DC2626', ls='--', lw=1.3, alpha=0.85, zorder=2)

    ax.set_xticks(x)
    ax.set_xticklabels(labels_geose, fontsize=10.8, fontweight='bold')
    ax.set_ylabel('Efficiency Score (0.0–1.0)', fontsize=11.5, fontweight='bold', labelpad=8)
    ax.tick_params(axis='y', labelsize=10.2)
    ax.tick_params(axis='x', length=0, pad=5)
    ax.set_ylim(0, 1.025)
    ax.spines['left'].set_bounds(0, 1.0)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.set_yticks([0.0, 0.2, 0.4, 0.6, 0.8, 1.0])
    ax.grid(axis='y', color='#E5E7EB', linestyle='--', linewidth=0.6, alpha=0.8, zorder=0)
    ax.grid(axis='x', visible=False)

    for i in range(len(labels_geose)):
        for val, offset, is_se in [(crs_vals[i], -w, False), (vrs_vals[i], 0, False), (se_vals[i], w, True)]:
            fontw = 'bold' if is_se else 'normal'
            color_txt = '#B45309' if is_se else '#1E293B'
            ax.text(i + offset, val + 0.015, f'{val:.2f}', ha='center', fontsize=9.8, fontweight=fontw, color=color_txt)

    ax.annotate("Scale mismatch primary constraint\n(Aegean & Marmara SE: 0.45 – 0.46)", 
                xy=(1.24, 0.48), xytext=(0.60, 0.85),
                ha='center', fontsize=9.6, fontweight='bold', color='#B45309',
                bbox=dict(boxstyle='round,pad=0.35', facecolor='#FEF3C7', edgecolor='#F59E0B', lw=0.9),
                arrowprops=dict(arrowstyle='->', connectionstyle='arc3,rad=-0.15', color='#B45309', lw=1.3))

    handles = [b1, b2, b3, Line2D([0], [0], color='#DC2626', ls='--', lw=1.3)]
    labels_legend = [
        'CRS Technical Efficiency (CCR)',
        'VRS Pure Technical Efficiency (BCC)',
        'Scale Efficiency (SE = CRS / VRS)',
        'Full Efficiency Frontier (1.0)'
    ]
    ax.legend(handles=handles, labels=labels_legend,
              fontsize=9.8, loc='upper center', bbox_to_anchor=(0.5, -0.13),
              ncol=4, framealpha=0.96, facecolor='white', edgecolor='#CBD5E1',
              columnspacing=1.0, handletextpad=0.45, borderaxespad=0.1)

    out_png = os.path.join(fig_dir, 'Fig5_scale_efficiency_decomposition.png')
    out_pdf = os.path.join(fig_dir, 'Fig5_scale_efficiency_decomposition.pdf')
    fig.savefig(out_png, dpi=300, bbox_inches='tight', pad_inches=0.03)
    fig.savefig(out_pdf, dpi=300, bbox_inches='tight', pad_inches=0.03)
    plt.close()
    print("  [✓] Successfully generated Figure 5 (PNG & PDF).")


# ==============================================================================
# FIGURE 6: Capacity Utilization & Modernization Index Biplot
# ==============================================================================
def generate_figure_6():
    print("Generating Figure 6 (Capacity Utilization & Biplot)...")
    res_json = os.path.join(data_dir, 'fleet_modernization_model_results.json')
    panel_csv = os.path.join(data_dir, 'panel_fisheries_modernization_2000_2024.csv')

    with open(res_json) as f:
        rb = json.load(f)

    panel = pd.read_csv(panel_csv)
    panel = panel[panel['Region'] != 'Total'].copy()
    if 'CU_Boot_BC' in panel.columns:
        panel['CU_Score'] = panel['CU_Boot_BC']

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(13.2, 5.8), dpi=300)

    dea = rb['dea']['by_region']
    means = [dea[r]['mean'] for r in GEO_REGIONS if r in dea]
    stds  = [dea[r]['std'] for r in GEO_REGIONS if r in dea]
    colors_bar = [GEO_COLORS[r] for r in GEO_REGIONS if r in dea]
    y_pos = range(len(GEO_REGIONS))

    ax_a.barh(y_pos, means, xerr=stds, height=0.55, color=colors_bar, alpha=0.90,
              edgecolor='white', lw=0.8, capsize=4.0, error_kw={'lw': 1.2, 'color': '#334155'})
    ax_a.axvline(1.0, color='#1E293B', ls='--', lw=1.0, alpha=0.6)
    ax_a.text(0.98, len(GEO_REGIONS)-0.4, 'Frontier (1.0)', fontsize=9.5, color='#64748B', ha='right', style='italic', fontweight='bold')
    ax_a.set_yticks(y_pos)
    ax_a.set_yticklabels([GEO_MAP.get(r, r) for r in GEO_REGIONS], fontsize=11.0, fontweight='bold')
    ax_a.set_xlabel('DEA Capacity Utilization Score', fontsize=12.0, fontweight='bold')
    ax_a.tick_params(axis='x', labelsize=10.5)
    ax_a.set_xlim(0, 1.20)
    for i, (m, s) in enumerate(zip(means, stds)):
        ax_a.text(m + s + 0.02, i, f'{m:.3f} ± {s:.3f}', va='center', fontsize=9.8, color='#1E293B', fontweight='bold')
    ax_a.text(-0.08, 1.06, '(a)', transform=ax_a.transAxes, fontsize=13.0, fontweight='bold', va='top')
    ax_a.set_title('Mean Capacity Utilization by Basin', loc='left', fontsize=12.5, fontweight='bold', pad=8)

    for reg in GEO_REGIONS:
        sub = panel[panel['Region'] == reg].dropna(subset=['Modernization_Index', 'CU_Score'])
        x = sub['Modernization_Index'].values
        y = sub['CU_Score'].values
        ax_b.scatter(x, y, color=GEO_COLORS[reg], s=56, alpha=0.90, label=GEO_MAP[reg], 
                     marker=GEO_MARKERS[reg], edgecolors='white', lw=0.7, zorder=4)
        if len(x) > 5:
            confidence_ellipse(x, y, ax_b, n_std=1.5, facecolor=GEO_COLORS[reg], edgecolor=GEO_COLORS[reg], 
                               lw=1.2, alpha=0.12, ls='--', zorder=2)

    xmid = panel['Modernization_Index'].median()
    ymid = panel['CU_Score'].median()
    ax_b.axvline(xmid, color='#94A3B8', ls=':', lw=1.0, alpha=0.7, zorder=1)
    ax_b.axhline(ymid, color='#94A3B8', ls=':', lw=1.0, alpha=0.7, zorder=1)

    mask = panel[['CU_Score', 'Modernization_Index']].dropna()
    z = np.polyfit(mask['Modernization_Index'], mask['CU_Score'], 1)
    x_line = np.linspace(mask['Modernization_Index'].min(), mask['Modernization_Index'].max(), 50)
    y_fit = np.polyval(z, x_line)
    ax_b.plot(x_line, y_fit, '-', color='#0F172A', lw=2.2, alpha=0.90, label='OLS Fit', zorder=5)

    ax_b.set_ylim(-0.06, 1.08)
    ax_b.set_xlim(-3.2, 4.2)
    ax_b.set_yticks([0.0, 0.2, 0.4, 0.6, 0.8, 1.0])
    ax_b.tick_params(axis='both', labelsize=10.5)

    ax_b.text(0.03, 0.97, "Quadrant II: Low MI / High CU\n(Traditional Scale Efficiency)", transform=ax_b.transAxes, va='top', ha='left', fontsize=9.2, color='#334155', style='italic', fontweight='bold',
              bbox=dict(boxstyle='round,pad=0.25', facecolor='#F8FAFC', edgecolor='#CBD5E1', lw=0.7, alpha=0.92))
    ax_b.text(0.97, 0.97, "Quadrant I: High MI / High CU\n(Frontier Performers)", transform=ax_b.transAxes, va='top', ha='right', fontsize=9.2, color='#334155', style='italic', fontweight='bold',
              bbox=dict(boxstyle='round,pad=0.25', facecolor='#F8FAFC', edgecolor='#CBD5E1', lw=0.7, alpha=0.92))
    ax_b.text(0.03, 0.03, "Quadrant III: Low MI / Low CU\n(Traditional Overcapacity)", transform=ax_b.transAxes, va='bottom', ha='left', fontsize=9.2, color='#334155', style='italic', fontweight='bold',
              bbox=dict(boxstyle='round,pad=0.25', facecolor='#F8FAFC', edgecolor='#CBD5E1', lw=0.7, alpha=0.92))
    ax_b.text(0.97, 0.03, "Quadrant IV: High MI / Low CU\n(Technology Treadmill)", transform=ax_b.transAxes, va='bottom', ha='right', fontsize=9.2, color='#334155', style='italic', fontweight='bold',
              bbox=dict(boxstyle='round,pad=0.25', facecolor='#F8FAFC', edgecolor='#CBD5E1', lw=0.7, alpha=0.92))

    ax_b.set_xlabel('Modernization Index (PCA Component 1)', fontsize=12.0, fontweight='bold')
    ax_b.set_ylabel('DEA Capacity Utilization Score', fontsize=12.0, fontweight='bold')
    ax_b.text(-0.08, 1.06, '(b)', transform=ax_b.transAxes, fontsize=13.0, fontweight='bold', va='top')
    ax_b.set_title('Modernization Index vs. Capacity Utilization', loc='left', fontsize=12.5, fontweight='bold', pad=8)

    handles_b, labels_b = ax_b.get_legend_handles_labels()
    fig.legend(handles_b, labels_b, loc='lower center', ncol=6, frameon=True, facecolor='white',
               edgecolor='#CBD5E1', fontsize=10.0, bbox_to_anchor=(0.50, -0.05))

    out_png = os.path.join(fig_dir, 'Fig6_DEA_CU_biplot.png')
    out_pdf = os.path.join(fig_dir, 'Fig6_DEA_CU_biplot.pdf')
    fig.savefig(out_png, dpi=300, bbox_inches='tight')
    fig.savefig(out_pdf, dpi=300, bbox_inches='tight')
    plt.close()
    print("  [✓] Successfully generated Figure 6 (PNG & PDF).")


# ==============================================================================
# MAIN EXECUTION ENTRY POINT
# ==============================================================================
def main():
    print("========================================================================")
    print("  GENERATING AUDITED PUBLICATION FIGURES FOR ICES JMS")
    print("========================================================================")
    generate_figure_2()
    generate_figure_3()
    generate_figure_4()
    generate_figure_5()
    generate_figure_6()
    print("========================================================================")
    print(f"  All figures saved in: {fig_dir}")
    print("========================================================================")


if __name__ == '__main__':
    main()
